### ISSUE TITLE
Unavailable conda channel

### ISSUE THREAD

**Issue by mjschlauch** [FeipengMa6/VSC22-Submission#1]
This environment relies on TenCent mirrors that are not widely accessible, which means the solution is not reproducible.

https://github.com/FeipengMa6/VSC22-Submission/blob/aa4ea0c71bade2b8eb337c69a7fe59c66255a8fa/VSC22-Descriptor-Track-2nd/environment.yml#L6-L12

```
Collecting package metadata (repodata.json): failed

UnavailableInvalidChannel: HTTP 404 NOT FOUND for channel anaconda/pkgs/main <https://mirrors.cloud.tencent.com/anaconda/pkgs/main>

The channel is not accessible or is invalid.
```

The environment.yml should be updated so that a typical user can getting a working environment up and running by following the steps in the README.

Similar issue on the Matching Track:
https://github.com/FeipengMa6/VSC22-Submission/blob/aa4ea0c71bade2b8eb337c69a7fe59c66255a8fa/VSC22-Matching-Track-1st/environment.yml#L6-L12

**Comment by edfall** [comment]
You can try accessing other Anaconda mirrors that are accessible from your network. If your server has unrestricted network access, it should be safe to remove these dependencies. For that anaconda will not impact the the result.

anyway, we will update it as soon as possible.

**Comment by FeipengMa6** [comment]
Hi, we apologize for the inconvenience caused and have fixed the issue. We retested the code in an initial environment to ensure its correctness. For your problem, we now offer two ways to build a runnable environment: [Dockerfile](https://github.com/FeipengMa6/VSC22-Submission/blob/main/dockerfile) or [command-line installation](https://github.com/FeipengMa6/VSC22-Submission/blob/main/setup.sh). We hope this resolves your issue.

**Comment by mjschlauch** [comment]
Thanks @edfall and @FeipengMa6! This addresses the issue.
