### ISSUE TITLE
Unrecognized arguments - video_score_train.py

### ISSUE THREAD

**Issue by mjschlauch** [FeipengMa6/VSC22-Submission#2]
In trying to reproduce this submission, I am getting an error when trying to run `train_vid_score.sh`.

https://github.com/FeipengMa6/VSC22-Submission/blob/55dd1a1fe138a46edbed082d5adedcbf6ff62800/VSC22-Descriptor-Track-2nd/train/train_vid_score/train_vid_score.sh#L7-L13

```
video_score_train.py: error: unrecognized arguments: --local-rank=1 --save_file ../../data/feat_zip/feats.zip --zip_prefix ../../data/jpg_zips --input_file ../../data/meta/vids.txt --clip_dir ../../checkpoints/clip_vit-l-14 --bs 8 --max_video_frames 256
```

It seems possible that we should be running the `extract_feat.py` script here, since that script takes these arguments.

Thank you for clarifying.

cc @FeipengMa6 @edfall

**Comment by FeipengMa6** [comment]
Yes, you are right. We'll update the code to make sure it's runnable.

**Comment by mjschlauch** [comment]
Thank you @FeipengMa6. Please also check for similar issues in other shell scripts and the remainder of the training process.

**Comment by FeipengMa6** [comment]
Sorry, @mjschlauch , I missed some preprocessed scripts in the previous check. I will retest them and remind you when they are finished.
