### ISSUE TITLE
Why does the Video Editing Detection helps improve uAP? 

### ISSUE THREAD

**Issue by FredHuang16** [FeipengMa6/VSC22-Submission#4]
Why does the VED module improve search results?  it seems theoretically reduces the effectiveness of search by reducing computational complexity.  Is there any special design behind it?

**Comment by FeipengMa6** [comment]
Good question!
There are three reasons:
1. Unedited videos are not copied videos at most situations.
2. There are reference videos that similar to the unedited videos. Unedited videos are hard negative samplers in this dataset, and drop these unedited videos during search can reduce false recalls.
3. Our VED can achieve a very high accuracy to detect unedited videos.
