### ISSUE TITLE
The question about the database

### ISSUE THREAD

**Issue by lst17640097780** [FeipengMa6/VSC22-Submission#6]
Thank you for your help. I didn't sign up for this competition, so I can't download the dataset now. 
Can you provide the dataset in some way? 
I'm much obliged!

**Comment by FeipengMa6** [comment]
Hi, you can participate in the [Video Similarity Challenge Open Arena](https://www.drivendata.org/competitions/219/competition-meta-vsc-desc-open/) to access the data.
